<<<<<<< HEAD
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
=======
import { SessionProviderComponent } from './components/SessionProvider'
import "./globals.css";

export default async function RootLayout({
>>>>>>> 188c174 (Prisma, NextAuth, SignOutPage/SignInPage)
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
=======
    <SessionProviderComponent>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </SessionProviderComponent>

>>>>>>> 188c174 (Prisma, NextAuth, SignOutPage/SignInPage)
  );
}
